language: dart
sudo: required
dist: xenial
# dart version mapped to flutter channel
dart:
  - stable
  - beta
  - dev
before_script:
  - cd repo_support
  - pub get
  - pub run tekartik_travis_ci_flutter:install
  - source $(pub run tekartik_travis_ci_flutter:env)
script:
  - dart tool/travis.dart
