name: tekartik_test_menu_flutter_repo
description: test_menu_flutter repo
version: 0.1.0
homepage: https://github.com/tekartik/sqflite

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  process_run: '>=0.10.0'
  tekartik_build_utils:
    git:
      url: https://github.com/tekartik/build_utils.dart
      ref: dart3a
    version: '>=0.7.1'
  test:
  dev_build:
  path:
  pub_semver:

dependency_overrides:
