name: tekartik_test_menu_flutter_repo
description: test_menu_flutter repo
version: 0.1.0
homepage: https://github.com/tekartik/sqflite

publish_to: none

environment:
  sdk: ^3.8.0

dev_dependencies:
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  path: ">=1.9.0"
  pub_semver: ">=2.1.4"

dependency_overrides:
resolution: workspace
dependencies:
  tekartik_prj_tktools:
    git:
      url: https://github.com/tekartikprj/tktools.git
      ref: dart3a
      path: packages/prj_tktools
  tekartik_build_utils:
    git:
      url: https://github.com/tekartik/build_utils.dart
      ref: dart3a
